import type { OrderModuleCode } from "./order-modules";

export type StandardRoadWorkflowCode =
  | "tms-road-pending"
  | "tms-default"
  | "tms-ftl-standard";

export type StandardRoadWorkflowModuleSeed = {
  stepKey: string;
  moduleCode: OrderModuleCode;
  displayName: string;
  sortOrder: number;
  required: boolean;
  responsibilityPositionCode: string;
  completionMode: "all_tasks" | "manual_confirm" | "automatic";
  taskKey: string;
  taskName: string;
  taskType: "form" | "review" | "decision" | "system";
  taskRequired: boolean;
  instructions: string | null;
};

/**
 * The factory defaults used only when an organization receives its first
 * road-order workflow. Runtime gates always use the frozen workflow instance,
 * so later workflow versions remain configurable without consulting this list.
 */
export const standardRoadWorkflowModules: readonly StandardRoadWorkflowModuleSeed[] = [
  {
    stepKey: "quotation",
    moduleCode: "consignment",
    displayName: "询价与报价",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "SALES",
    completionMode: "all_tasks",
    taskKey: "handle_quotation",
    taskName: "填写询价并完成报价",
    taskType: "system",
    taskRequired: true,
    instructions: "首次保存报价时锁定工作流版本；客户接受后完成本节点。",
  },
  {
    stepKey: "order_creation",
    moduleCode: "consignment",
    displayName: "委托信息",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "SALES",
    completionMode: "all_tasks",
    taskKey: "handle_consignment",
    taskName: "补齐委托资料并提请审批",
    taskType: "form",
    taskRequired: true,
    instructions: "按当前工作流字段规则补齐资料后提请审批。",
  },
  {
    stepKey: "order_creation",
    moduleCode: "cargo",
    displayName: "货物信息",
    sortOrder: 20,
    required: false,
    responsibilityPositionCode: "SALES",
    completionMode: "all_tasks",
    taskKey: "handle_cargo",
    taskName: "维护货物信息",
    taskType: "form",
    taskRequired: true,
    instructions: "按当前工作流字段规则维护货物信息；本模块默认不阻断。",
  },
  {
    stepKey: "order_creation",
    moduleCode: "costs",
    displayName: "预录费用",
    sortOrder: 30,
    required: false,
    responsibilityPositionCode: "FINANCE_ACCOUNTING",
    completionMode: "all_tasks",
    taskKey: "handle_costs",
    taskName: "预录应收应付费用",
    taskType: "form",
    taskRequired: true,
    instructions: "需要时预录费用；本模块默认不阻断委托提交。",
  },
  {
    stepKey: "consignment_approval",
    moduleCode: "consignment",
    displayName: "委托审核",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "BUSINESS_SUPERVISOR",
    completionMode: "manual_confirm",
    taskKey: "handle_consignment",
    taskName: "审核委托资料",
    taskType: "review",
    taskRequired: true,
    instructions: "核对委托资料并明确通过或退回。",
  },
  {
    stepKey: "task_assignment",
    moduleCode: "assignment",
    displayName: "任务分配",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "OPERATION_SUPERVISOR",
    completionMode: "all_tasks",
    taskKey: "handle_assignment",
    taskName: "按工作流分配具体负责人",
    taskType: "form",
    taskRequired: true,
    instructions: "为锁定工作流中的每个必办责任组指定有效个人账户。",
  },
  {
    stepKey: "domestic_execution",
    moduleCode: "transport",
    displayName: "国内运输",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "OPERATION",
    completionMode: "all_tasks",
    taskKey: "handle_transport",
    taskName: "办理国内运输",
    taskType: "form",
    taskRequired: true,
    instructions: "安排提货车辆、司机、承运方并推进至国内仓。",
  },
  {
    stepKey: "warehouse_receiving",
    moduleCode: "warehouse",
    displayName: "国内仓入库",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "WAREHOUSE",
    completionMode: "all_tasks",
    taskKey: "handle_warehouse",
    taskName: "完成国内仓收货入库",
    taskType: "form",
    taskRequired: true,
    instructions: "收货、清点、称重量方并完成入库。",
  },
  {
    stepKey: "port_loading",
    moduleCode: "loading",
    displayName: "装车与出库",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "WAREHOUSE",
    completionMode: "all_tasks",
    taskKey: "handle_loading",
    taskName: "完成装车出库",
    taskType: "form",
    taskRequired: true,
    instructions: "按整车或配载单完成扫码装车、出库与交接。",
  },
  {
    stepKey: "outbound_transport",
    moduleCode: "documents",
    displayName: "报关文件",
    sortOrder: 10,
    required: false,
    responsibilityPositionCode: "DOC",
    completionMode: "all_tasks",
    taskKey: "handle_documents",
    taskName: "整理报关与发运文件",
    taskType: "form",
    taskRequired: true,
    instructions: "按配置整理、审核并归档订单文件；本模块默认不单独阻断。",
  },
  {
    stepKey: "outbound_transport",
    moduleCode: "customs",
    displayName: "报关作业",
    sortOrder: 20,
    required: true,
    responsibilityPositionCode: "DOC",
    completionMode: "all_tasks",
    taskKey: "handle_customs",
    taskName: "办理报关并确认放行",
    taskType: "form",
    taskRequired: true,
    instructions: "核对资料、申报并登记海关放行后方可确认实际出境。",
  },
  {
    stepKey: "outbound_transport",
    moduleCode: "tracking",
    displayName: "出境运输与运踪",
    sortOrder: 30,
    required: true,
    responsibilityPositionCode: "OPERATION",
    completionMode: "all_tasks",
    taskKey: "handle_tracking",
    taskName: "登记实际出境与运踪",
    taskType: "form",
    taskRequired: true,
    instructions: "按顺序登记口岸到达、实际出境及后续境外运输节点。",
  },
  {
    stepKey: "overseas_pickup",
    moduleCode: "overseas_warehouse",
    displayName: "境外仓与客户自提",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "OVERSEAS_WAREHOUSE",
    completionMode: "all_tasks",
    taskKey: "handle_overseas_warehouse",
    taskName: "完成境外仓入库与客户自提签收",
    taskType: "form",
    taskRequired: true,
    instructions: "登记境外仓到仓，通知客户并完成扫码自提签收。",
  },
  {
    stepKey: "reconciliation",
    moduleCode: "costs",
    displayName: "三方费用结算",
    sortOrder: 10,
    required: true,
    responsibilityPositionCode: "CS",
    completionMode: "all_tasks",
    taskKey: "handle_costs",
    taskName: "完成三方费用确认与结算",
    taskType: "form",
    taskRequired: true,
    instructions: "按配置完成客服、业务、财务确认及必要的结算凭证。",
  },
  {
    stepKey: "completion_review",
    moduleCode: "exceptions",
    displayName: "异常处理",
    sortOrder: 10,
    required: false,
    responsibilityPositionCode: "OPERATION",
    completionMode: "all_tasks",
    taskKey: "handle_exceptions",
    taskName: "处理并关闭业务异常",
    taskType: "form",
    taskRequired: true,
    instructions: "有异常时完成处理与复核；无异常时本模块不阻断。",
  },
  {
    stepKey: "completion_review",
    moduleCode: "review",
    displayName: "订单复盘",
    sortOrder: 20,
    required: true,
    responsibilityPositionCode: "FINANCE_ACCOUNTING",
    completionMode: "manual_confirm",
    taskKey: "handle_review",
    taskName: "复盘并确认归档",
    taskType: "review",
    taskRequired: true,
    instructions: "复核时效、费用、利润、异常和资料完整性后明确确认归档。",
  },
] as const;

export function standardRoadWorkflowType(code: StandardRoadWorkflowCode) {
  return code === "tms-ftl-standard" ? "ftl" : "ltl";
}
