PRAGMA foreign_keys = ON;

ALTER TABLE users ADD COLUMN phone TEXT;
ALTER TABLE users ADD COLUMN locale TEXT NOT NULL DEFAULT 'zh-CN';
ALTER TABLE users ADD COLUMN timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai';
