import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("setup", "routes/setup.tsx"),
  route("login", "routes/login.tsx"),
  route("portal/login", "routes/portal.login.tsx"),
  route("portal/register", "routes/portal.register.tsx"),
  route("warehouse/login", "routes/warehouse.login.tsx"),
  route("logout", "routes/logout.tsx"),
  layout("routes/dashboard.tsx", [
    route("admin", "routes/dashboard.index.tsx"),
    route("admin/portal", "routes/admin.position-portal.tsx"),
    route("admin/notifications", "routes/admin.notifications.tsx"),
    route("admin/master-data", "routes/admin.master-data.tsx"),
    route("admin/customers", "routes/admin.customers.tsx"),
    route(
      "admin/customer-contracts/:contractId/download",
      "routes/admin.customer-contract-download.ts",
    ),
    route("admin/sales", "routes/admin.sales.tsx"),
    route("admin/quotations", "routes/admin.quotations.tsx"),
    route(
      "admin/quotation-field-files/:valueId",
      "routes/admin.quotation-field-file.ts",
    ),
    route("admin/logistics-products", "routes/admin.logistics-products.tsx"),
    route("admin/carriers", "routes/admin.carriers.tsx"),
    route("admin/orders", "routes/admin.orders.tsx"),
    route("admin/domestic-tracking", "routes/admin.domestic-tracking.tsx"),
    route("admin/documents", "routes/admin.documents.tsx"),
    route(
      "admin/document-files/:sourceType/:fileId",
      "routes/admin.document-file.ts",
    ),
    route("admin/cargo-images/:imageId", "routes/admin.cargo-image.ts"),
    route("admin/cargo", "routes/admin.cargo.tsx"),
    route("admin/loading", "routes/admin.loading.tsx"),
    route("admin/loading/:batchId", "routes/admin.loading-detail.tsx"),
    route(
      "admin/workbenches/:workspace",
      "routes/admin.order-workbench.tsx",
    ),
    route(
      "admin/orders/:orderId/operations",
      "routes/admin.order-operations.tsx",
    ),
    route(
      "admin/orders/:orderId/packages/print",
      "routes/admin.package-labels.tsx",
    ),
    route(
      "admin/orders/:orderId/mark-label",
      "routes/admin.order-mark-label.tsx",
    ),
    route(
      "admin/orders/:orderId/mark-label/download",
      "routes/admin.order-mark-label-download.ts",
    ),
    route(
      "admin/orders/:orderId/modules/:moduleCode",
      "routes/admin.order-module.tsx",
    ),
    route("admin/orders/:orderId", "routes/admin.order-detail.tsx"),
    route("admin/shipments", "routes/admin.shipments.tsx"),
    route("admin/billing", "routes/admin.billing.tsx"),
    route("admin/workflow", "routes/admin.workflow.tsx"),
    route("admin/warehouses", "routes/admin.warehouses.tsx"),
    route("admin/departments", "routes/admin.departments.tsx"),
    route("admin/positions", "routes/admin.positions.tsx"),
    route("admin/users", "routes/dashboard.users.tsx"),
    route("admin/roles", "routes/dashboard.roles.tsx"),
    route("admin/security", "routes/admin.security.tsx"),
    route("admin/audit", "routes/dashboard.audit.tsx"),
  ]),
  layout("routes/portal.tsx", [
    route("portal", "routes/portal.index.tsx"),
    route("portal/calculator", "routes/portal.calculator.tsx"),
    route("portal/quotes", "routes/portal.quotes.tsx"),
    route("portal/orders", "routes/portal.orders.tsx"),
    route(
      "portal/pickup-appointment",
      "routes/portal.pickup-appointment.tsx",
    ),
    route(
      "portal/orders/:orderId/mark-label",
      "routes/portal.order-mark-label.tsx",
    ),
    route(
      "portal/orders/:orderId/mark-label/download",
      "routes/portal.order-mark-label-download.ts",
    ),
    route("portal/tracking", "routes/portal.tracking.tsx"),
    route("portal/billing", "routes/portal.billing.tsx"),
    route("portal/notifications", "routes/portal.notifications.tsx"),
    route("portal/account", "routes/portal.account.tsx"),
  ]),
  route(
    "portal/invoices/:invoiceId/download",
    "routes/portal.invoice-download.ts",
  ),
  route("switch-site", "routes/switch-site.ts"),
  route("warehouse/order-module", "routes/warehouse.order-module.ts"),
  route(
    "warehouse/document-files/:sourceType/:fileId",
    "routes/warehouse.document-file.ts",
  ),
  layout("routes/warehouse.tsx", [
    route("warehouse", "routes/warehouse.index.tsx"),
    route("warehouse/inbound", "routes/warehouse.inbound.tsx"),
    route("warehouse/acceptance", "routes/warehouse.acceptance.tsx"),
    route("warehouse/sorting", "routes/warehouse.sorting.tsx"),
    route("warehouse/consolidation", "routes/warehouse.cargo-consolidation.tsx"),
    route("warehouse/loading-documents", "routes/warehouse.loading-documents.tsx"),
    route("warehouse/outbound", "routes/warehouse.outbound.tsx"),
    route("warehouse/pickup", "routes/warehouse.pickup.tsx"),
    route("warehouse/inventory", "routes/warehouse.inventory.tsx"),
    route("warehouse/exceptions", "routes/warehouse.exceptions.tsx"),
    route("warehouse/locations", "routes/warehouse.locations.tsx"),
  ]),
  route("dashboard", "routes/legacy.admin.tsx"),
] satisfies RouteConfig;
