import { env } from "cloudflare:workers";
import type { Route } from "./+types/portal.notifications";
import { PortalForm as Form, PortalLink as Link } from "../components/PortalNavigation";
import { ActionToast } from "../components/ActionToast";
import { requirePortalCustomer } from "../lib/portal.server";
import { normalizePortalNotificationLink } from "../lib/portal-notification-links";

type Notice={id:string;type:string;title:string;message:string;link:string|null;is_read:number;created_at:string};
type Pref={email_quote:number;email_order:number;email_shipment:number;email_invoice:number;email_payment:number;in_app_enabled:number};
const typeLabels:Record<string,string>={quote:"报价",order:"订单",shipment:"运输",invoice:"账单",payment:"付款",system:"系统"};
export async function loader({request}:Route.LoaderArgs){const{user,customer}=await requirePortalCustomer(request);const[notices,pref]=await Promise.all([env.DB.prepare("SELECT id,type,title,message,link,is_read,created_at FROM portal_notifications WHERE organization_id=? AND customer_id=? AND (user_id IS NULL OR user_id=?) ORDER BY created_at DESC LIMIT 100").bind(user.organizationId,customer.id,user.userId).all<Notice>(),env.DB.prepare("SELECT email_quote,email_order,email_shipment,email_invoice,email_payment,in_app_enabled FROM portal_notification_preferences WHERE organization_id=? AND user_id=?").bind(user.organizationId,user.userId).first<Pref>()]);return{notices:notices.results,pref:pref??{email_quote:1,email_order:1,email_shipment:1,email_invoice:1,email_payment:1,in_app_enabled:1}}}
export async function action({request}:Route.ActionArgs){const{user,customer}=await requirePortalCustomer(request),form=await request.formData(),intent=String(form.get("intent")??""),now=new Date().toISOString();if(intent==="read"){await env.DB.prepare("UPDATE portal_notifications SET is_read=1,read_at=? WHERE id=? AND organization_id=? AND customer_id=? AND (user_id IS NULL OR user_id=?)").bind(now,String(form.get("id")??""),user.organizationId,customer.id,user.userId).run();return{success:"消息已读"}}if(intent==="read_all"){await env.DB.prepare("UPDATE portal_notifications SET is_read=1,read_at=? WHERE organization_id=? AND customer_id=? AND (user_id IS NULL OR user_id=?) AND is_read=0").bind(now,user.organizationId,customer.id,user.userId).run();return{success:"已全部标记为已读"}}if(intent==="preferences"){const checked=(name:string)=>form.get(name)==="1"?1:0;await env.DB.prepare(`INSERT INTO portal_notification_preferences(id,organization_id,user_id,email_quote,email_order,email_shipment,email_invoice,email_payment,in_app_enabled,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(organization_id,user_id) DO UPDATE SET email_quote=excluded.email_quote,email_order=excluded.email_order,email_shipment=excluded.email_shipment,email_invoice=excluded.email_invoice,email_payment=excluded.email_payment,in_app_enabled=excluded.in_app_enabled,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),user.organizationId,user.userId,checked("email_quote"),checked("email_order"),checked("email_shipment"),checked("email_invoice"),checked("email_payment"),checked("in_app_enabled"),now).run();return{success:"通知偏好已保存"}}return{formError:"无效操作"}}
export default function PortalNotifications({loaderData,actionData}:Route.ComponentProps){const unread=loaderData.notices.filter(x=>!x.is_read).length;return <><header className="page-header"><div><p className="eyebrow">NOTIFICATIONS</p><h1>通知</h1><p>集中查看报价、运输、账单和付款进度通知。</p></div><Form method="post"><input type="hidden" name="intent" value="read_all"/><button className="secondary" disabled={!unread}>全部已读（{unread}）</button></Form></header><ActionToast data={actionData}/><div className="notification-layout"><section className="panel"><div className="notification-list">{loaderData.notices.map(n=><article className={n.is_read?"":"unread"} key={n.id}><span className="status-pill">{typeLabels[n.type]??n.type}</span><div><h3>{n.title}</h3><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString("zh-CN")}</small></div><div className="page-actions">{n.link&&<Link className="text-button" to={normalizePortalNotificationLink(n.link)??n.link}>查看</Link>}{!n.is_read&&<Form method="post"><input type="hidden" name="intent" value="read"/><input type="hidden" name="id" value={n.id}/><button className="text-button">标为已读</button></Form>}</div></article>)}</div>{!loaderData.notices.length&&<p className="empty-state">暂无通知。</p>}</section><section className="panel preference-panel"><h2>通知偏好</h2><p className="muted">站内消息会保留在门户中；邮件通知将在邮件服务接入后按此设置发送。</p><Form method="post" className="stack"><input type="hidden" name="intent" value="preferences"/><Preference name="in_app_enabled" label="启用站内消息" value={loaderData.pref.in_app_enabled}/><Preference name="email_quote" label="报价邮件" value={loaderData.pref.email_quote}/><Preference name="email_order" label="订单邮件" value={loaderData.pref.email_order}/><Preference name="email_shipment" label="运输节点邮件" value={loaderData.pref.email_shipment}/><Preference name="email_invoice" label="账单邮件" value={loaderData.pref.email_invoice}/><Preference name="email_payment" label="付款审核邮件" value={loaderData.pref.email_payment}/><button className="primary portal-primary">保存偏好</button></Form></section></div></>}
function Preference({name,label,value}:{name:string;label:string;value:number}){return <label className="check-field"><input type="checkbox" name={name} value="1" defaultChecked={Boolean(value)}/>{label}</label>}
export function meta(){return[{title:"通知 | 新翎航客户门户"}]}
