import { env } from "cloudflare:workers";
import { Form, Link, useNavigation } from "react-router";
import type { Route } from "./+types/portal.account";
import { Modal } from "../components/Modal";
import { requirePortalCustomer } from "../lib/portal.server";
import { hashPassword, verifyPassword } from "../lib/crypto.server";
import { validateEmail, validatePassword, valueOf } from "../lib/validation";
import { writeAudit } from "../lib/audit.server";
import { customerBusinessRoleLabel } from "../lib/customer-business-roles";

type Profile={display_name:string;email:string;phone:string|null;locale:string;timezone:string;last_login_at:string|null};
type Company={code:string;name:string;short_name:string|null;business_role_codes:string;tax_id:string|null;website:string|null;industry:string|null;status:string;sales_owner:string|null};
type Contact={id:string;name:string;title:string|null;email:string|null;phone:string|null;is_primary:number};
type Address={id:string;type:string;label:string;country_code:string;state:string|null;city:string;postal_code:string|null;address_line1:string;address_line2:string|null;contact_name:string|null;contact_phone:string|null;is_default:number};

export async function loader({request}:Route.LoaderArgs){const{user,customer}=await requirePortalCustomer(request),tab=new URL(request.url).searchParams.get("tab")??"profile";const[profile,company,contacts,addresses,countries]=await Promise.all([
  env.DB.prepare("SELECT display_name,email,phone,locale,timezone,last_login_at FROM users WHERE id=?").bind(user.userId).first<Profile>(),
  env.DB.prepare(`SELECT c.code,c.name,c.short_name,c.tax_id,c.website,c.industry,c.status,u.display_name sales_owner,COALESCE((SELECT GROUP_CONCAT(role_code) FROM customer_business_role_assignments WHERE organization_id=c.organization_id AND customer_id=c.id),'') business_role_codes FROM customers c LEFT JOIN users u ON u.id=c.sales_owner_user_id WHERE c.id=? AND c.organization_id=?`).bind(customer.id,user.organizationId).first<Company>(),
  env.DB.prepare("SELECT id,name,title,email,phone,is_primary FROM customer_contacts WHERE customer_id=? ORDER BY is_primary DESC,name").bind(customer.id).all<Contact>(),
  env.DB.prepare("SELECT id,type,label,country_code,state,city,postal_code,address_line1,address_line2,contact_name,contact_phone,is_default FROM customer_addresses WHERE customer_id=? ORDER BY is_default DESC,label").bind(customer.id).all<Address>(),
  env.DB.prepare("SELECT code,name FROM reference_data WHERE organization_id=? AND category='country' AND status='active' ORDER BY sort_order,name").bind(user.organizationId).all<{code:string;name:string}>()
]);if(!profile||!company)throw new Response("账户资料不存在",{status:404});return{user,customer,tab,profile,company,contacts:contacts.results,addresses:addresses.results,countries:countries.results}}

export async function action({request}:Route.ActionArgs){const{user,customer}=await requirePortalCustomer(request),form=await request.formData(),intent=valueOf(form,"intent"),now=new Date().toISOString();
  if(intent==="profile"){const name=valueOf(form,"displayName"),phone=valueOf(form,"phone"),locale=valueOf(form,"locale"),timezone=valueOf(form,"timezone");if(name.length<2||name.length>80||phone.length>30||!["zh-CN","en-US","ru-RU"].includes(locale)||!["Asia/Shanghai","Asia/Tashkent","Europe/Moscow","UTC"].includes(timezone))return{formError:"请填写有效的个人资料"};await env.DB.prepare("UPDATE users SET display_name=?,phone=?,locale=?,timezone=?,updated_at=? WHERE id=?").bind(name,phone||null,locale,timezone,now,user.userId).run();await writeAudit({request,action:"portal.profile.update",resourceType:"user",resourceId:user.userId,organizationId:user.organizationId,actorUserId:user.userId});return{success:"个人资料已更新"};}
  if(intent==="password"){const current=valueOf(form,"currentPassword"),password=valueOf(form,"newPassword"),confirm=valueOf(form,"confirmPassword"),row=await env.DB.prepare("SELECT password_hash FROM users WHERE id=?").bind(user.userId).first<{password_hash:string}>();if(!row||!(await verifyPassword(current,row.password_hash)))return{formError:"当前密码不正确"};const error=validatePassword(password);if(error)return{formError:error};if(password!==confirm)return{formError:"两次输入的新密码不一致"};if(await verifyPassword(password,row.password_hash))return{formError:"新密码不能与当前密码相同"};await env.DB.batch([env.DB.prepare("UPDATE users SET password_hash=?,failed_login_count=0,locked_until=NULL,updated_at=? WHERE id=?").bind(await hashPassword(password),now,user.userId),env.DB.prepare("DELETE FROM sessions WHERE user_id=? AND id<>?").bind(user.userId,user.sessionId)]);await writeAudit({request,action:"portal.password.change",resourceType:"user",resourceId:user.userId,organizationId:user.organizationId,actorUserId:user.userId});return{success:"密码已修改，其他设备已退出登录"};}
  if(intent==="contact_save"){const id=valueOf(form,"id"),name=valueOf(form,"name"),title=valueOf(form,"title"),email=valueOf(form,"email"),phone=valueOf(form,"phone"),primary=valueOf(form,"isPrimary")==="1";if(name.length<2||name.length>80||email&&validateEmail(email)||phone.length>30)return{formError:"请填写有效的联系人资料"};if(primary)await env.DB.prepare("UPDATE customer_contacts SET is_primary=0,updated_at=? WHERE customer_id=?").bind(now,customer.id).run();if(id){const found=await env.DB.prepare("SELECT id FROM customer_contacts WHERE id=? AND customer_id=?").bind(id,customer.id).first();if(!found)return{formError:"联系人不存在"};await env.DB.prepare("UPDATE customer_contacts SET name=?,title=?,email=?,phone=?,is_primary=?,updated_at=? WHERE id=? AND customer_id=?").bind(name,title||null,email||null,phone||null,primary?1:0,now,id,customer.id).run();}else await env.DB.prepare("INSERT INTO customer_contacts(id,customer_id,name,title,email,phone,is_primary,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),customer.id,name,title||null,email||null,phone||null,primary?1:0,now,now).run();return{success:id?"联系人已更新":"联系人已新增"};}
  if(intent==="contact_delete"){const id=valueOf(form,"id");await env.DB.prepare("DELETE FROM customer_contacts WHERE id=? AND customer_id=?").bind(id,customer.id).run();return{success:"联系人已删除"};}
  if(intent==="address_save"){const id=valueOf(form,"id"),type=valueOf(form,"type"),label=valueOf(form,"label"),country=valueOf(form,"country"),state=valueOf(form,"state"),city=valueOf(form,"city"),postal=valueOf(form,"postal"),line1=valueOf(form,"line1"),line2=valueOf(form,"line2"),contact=valueOf(form,"contact"),phone=valueOf(form,"phone"),isDefault=valueOf(form,"isDefault")==="1";if(!["registered","billing","shipping","warehouse"].includes(type)||![label,country,city,line1].every(Boolean))return{formError:"请填写完整的地址资料"};if(isDefault)await env.DB.prepare("UPDATE customer_addresses SET is_default=0,updated_at=? WHERE customer_id=? AND type=?").bind(now,customer.id,type).run();if(id){const found=await env.DB.prepare("SELECT id FROM customer_addresses WHERE id=? AND customer_id=?").bind(id,customer.id).first();if(!found)return{formError:"地址不存在"};await env.DB.prepare("UPDATE customer_addresses SET type=?,label=?,country_code=?,state=?,city=?,postal_code=?,address_line1=?,address_line2=?,contact_name=?,contact_phone=?,is_default=?,updated_at=? WHERE id=? AND customer_id=?").bind(type,label,country,state||null,city,postal||null,line1,line2||null,contact||null,phone||null,isDefault?1:0,now,id,customer.id).run();}else await env.DB.prepare("INSERT INTO customer_addresses(id,customer_id,type,label,country_code,state,city,postal_code,address_line1,address_line2,contact_name,contact_phone,is_default,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),customer.id,type,label,country,state||null,city,postal||null,line1,line2||null,contact||null,phone||null,isDefault?1:0,now,now).run();return{success:id?"地址已更新":"地址已新增"};}
  if(intent==="address_delete"){await env.DB.prepare("DELETE FROM customer_addresses WHERE id=? AND customer_id=?").bind(valueOf(form,"id"),customer.id).run();return{success:"地址已删除"};}
  return{formError:"无效的账户操作"};}

const tabs=[["profile","我的资料"],["company","企业资料"],["contacts","联系人"],["addresses","地址簿"],["security","安全设置"]] as const,addressTypes:Record<string,string>={registered:"注册地址",billing:"账单地址",shipping:"收发货地址",warehouse:"仓库地址"};
export default function PortalAccount({loaderData,actionData}:Route.ComponentProps){const busy=useNavigation().state!=="idle";return <><header className="page-header"><div><p className="eyebrow">ACCOUNT CENTER</p><h1>账户中心</h1><p>维护个人资料、企业联系人、常用地址和登录安全。</p></div></header><nav className="tabs account-tabs">{tabs.map(([code,label])=><Link key={code} className={loaderData.tab===code?"active":""} to={`?tab=${code}`}>{label}</Link>)}</nav>{(actionData?.success||actionData?.formError)&&<div className={`alert ${actionData.formError?"error":"success"}`}>{actionData.formError??actionData.success}</div>}
{loaderData.tab==="profile"&&<section className="panel account-panel"><div className="panel-header"><div><h2>我的资料</h2><p>登录邮箱不可自行修改，如需变更请联系管理员。</p></div></div><Form method="post" className="form-grid compact account-profile-form"><input type="hidden" name="intent" value="profile"/><label className="field"><span>姓名</span><input name="displayName" defaultValue={loaderData.profile.display_name} required/></label><label className="field account-profile-email"><span>登录邮箱</span><input value={loaderData.profile.email} readOnly/></label><label className="field"><span>联系电话</span><input name="phone" defaultValue={loaderData.profile.phone??""}/></label><label className="field"><span>界面语言</span><select name="locale" defaultValue={loaderData.profile.locale}><option value="zh-CN">简体中文</option><option value="en-US">English</option><option value="ru-RU">Русский</option></select></label><label className="field account-profile-timezone"><span>时区</span><select name="timezone" defaultValue={loaderData.profile.timezone}><option value="Asia/Shanghai">中国时间</option><option value="Asia/Tashkent">乌兹别克斯坦时间</option><option value="Europe/Moscow">莫斯科时间</option><option value="UTC">UTC</option></select></label><label className="field account-profile-login"><span>最近登录</span><input value={loaderData.profile.last_login_at?new Date(loaderData.profile.last_login_at).toLocaleString("zh-CN"):"暂无记录"} readOnly/></label><button className="primary portal-primary" disabled={busy}>保存个人资料</button></Form></section>}
{loaderData.tab==="company"&&<section className="panel"><div className="panel-header"><div><h2>企业资料</h2><p>企业核心资料由欧凌后台维护。</p></div><span className="status-pill">{loaderData.company.status==="active"?"正常":"受限"}</span></div><div className="company-profile"><Info label="客户名称" value={loaderData.company.name}/><Info label="客户识别码" value={loaderData.company.code}/><Info label="简称" value={loaderData.company.short_name}/><Info label="客户类型" value={loaderData.company.business_role_codes.split(",").filter(Boolean).map(customerBusinessRoleLabel).join("、")}/><Info label="税号" value={loaderData.company.tax_id}/><Info label="行业" value={loaderData.company.industry}/><Info label="网站" value={loaderData.company.website}/><Info label="销售负责人" value={loaderData.company.sales_owner}/></div></section>}
{loaderData.tab==="contacts"&&<section className="panel"><div className="panel-header"><div><h2>联系人</h2><p>维护业务、财务和收发货联系人。</p></div><Modal title="新增联系人" triggerLabel="＋ 新增联系人" closeSignal={actionData?.success}><ContactForm busy={busy}/></Modal></div><div className="account-list">{loaderData.contacts.map(item=><div key={item.id}><div><strong>{item.name}{item.is_primary?" · 主要联系人":""}</strong><small>{item.title||"未设置职位"}</small></div><span>{item.email||"—"}<small>{item.phone||"—"}</small></span><div className="page-actions"><Modal title={`编辑 ${item.name}`} triggerLabel="编辑" triggerClassName="text-button" closeSignal={actionData?.success}><ContactForm contact={item} busy={busy}/></Modal><Form method="post"><input type="hidden" name="intent" value="contact_delete"/><input type="hidden" name="id" value={item.id}/><button className="text-button danger">删除</button></Form></div></div>)}</div>{!loaderData.contacts.length&&<p className="empty-state">暂无联系人。</p>}</section>}
{loaderData.tab==="addresses"&&<section className="panel"><div className="panel-header"><div><h2>地址簿</h2><p>运输需求可复用的常用收发货地址。</p></div><Modal title="新增地址" triggerLabel="＋ 新增地址" closeSignal={actionData?.success} size="wide"><AddressForm countries={loaderData.countries} busy={busy}/></Modal></div><div className="address-grid">{loaderData.addresses.map(item=><article className="address-card" key={item.id}><header><span className="status-pill">{addressTypes[item.type]}</span>{item.is_default&&<b>默认</b>}</header><h3>{item.label}</h3><p>{item.country_code} {item.state} {item.city} {item.address_line1} {item.address_line2}</p><small>{item.contact_name||"—"} · {item.contact_phone||"—"}</small><footer><Modal title={`编辑 ${item.label}`} triggerLabel="编辑" triggerClassName="text-button" closeSignal={actionData?.success} size="wide"><AddressForm address={item} countries={loaderData.countries} busy={busy}/></Modal><Form method="post"><input type="hidden" name="intent" value="address_delete"/><input type="hidden" name="id" value={item.id}/><button className="text-button danger">删除</button></Form></footer></article>)}</div>{!loaderData.addresses.length&&<p className="empty-state">暂无常用地址。</p>}</section>}
{loaderData.tab==="security"&&<section className="panel account-panel"><div className="panel-header"><div><h2>修改密码</h2><p>修改成功后，其他设备上的登录会话将自动退出。</p></div></div><Form method="post" className="stack security-form"><input type="hidden" name="intent" value="password"/><label className="field"><span>当前密码</span><input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="field"><span>新密码</span><input name="newPassword" type="password" autoComplete="new-password" required/><small>至少 12 位，必须包含大小写字母和数字。</small></label><label className="field"><span>确认新密码</span><input name="confirmPassword" type="password" autoComplete="new-password" required/></label><button className="primary portal-primary" disabled={busy}>修改密码</button></Form></section>}</>}

function ContactForm({contact,busy}:{contact?:Contact;busy:boolean}){return <Form method="post" className="stack"><input type="hidden" name="intent" value="contact_save"/>{contact&&<input type="hidden" name="id" value={contact.id}/>}<label className="field"><span>姓名</span><input name="name" defaultValue={contact?.name} required/></label><label className="field"><span>职位</span><input name="title" defaultValue={contact?.title??""}/></label><label className="field"><span>邮箱</span><input name="email" type="email" defaultValue={contact?.email??""}/></label><label className="field"><span>电话</span><input name="phone" defaultValue={contact?.phone??""}/></label><label className="check-field"><input name="isPrimary" type="checkbox" value="1" defaultChecked={Boolean(contact?.is_primary)}/>设为主要联系人</label><button className="primary portal-primary" disabled={busy}>保存联系人</button></Form>}
function AddressForm({address,countries,busy}:{address?:Address;countries:{code:string;name:string}[];busy:boolean}){return <Form method="post" className="form-grid compact"><input type="hidden" name="intent" value="address_save"/>{address&&<input type="hidden" name="id" value={address.id}/>}<label className="field"><span>地址类型</span><select name="type" defaultValue={address?.type??"shipping"}>{Object.entries(addressTypes).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className="field"><span>地址名称</span><input name="label" defaultValue={address?.label} placeholder="例如：乌鲁木齐仓库" required/></label><label className="field"><span>国家</span><select name="country" defaultValue={address?.country_code??"CN"}>{countries.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><label className="field"><span>省/州</span><input name="state" defaultValue={address?.state??""}/></label><label className="field"><span>城市</span><input name="city" defaultValue={address?.city} required/></label><label className="field"><span>邮编</span><input name="postal" defaultValue={address?.postal_code??""}/></label><label className="field span-2"><span>详细地址</span><input name="line1" defaultValue={address?.address_line1} required/></label><label className="field span-2"><span>地址补充</span><input name="line2" defaultValue={address?.address_line2??""}/></label><label className="field"><span>联系人</span><input name="contact" defaultValue={address?.contact_name??""}/></label><label className="field"><span>联系电话</span><input name="phone" defaultValue={address?.contact_phone??""}/></label><label className="check-field span-2"><input name="isDefault" type="checkbox" value="1" defaultChecked={Boolean(address?.is_default)}/>设为该类型默认地址</label><button className="primary portal-primary" disabled={busy}>保存地址</button></Form>}
function Info({label,value}:{label:string;value:string|null|undefined}){return <div><span>{label}</span><strong>{value||"—"}</strong></div>}
export function meta(){return[{title:"账户中心 | 欧凌客户门户"}]}
