import { env } from "cloudflare:workers";
import type { Route } from "./+types/portal.tracking";
import { requirePortalCustomer } from "../lib/portal.server";
type Shipment={id:string;shipment_number:string;order_number:string;status:string;current_location:string|null;estimated_delivery_at:string|null;actual_delivery_at:string|null;signed_by:string|null;origin_city:string;destination_city:string;cargo_description:string};
type Event={id:string;shipment_id:string;status:string;location:string|null;description:string;event_at:string};
export async function loader({request}:Route.LoaderArgs){const {user,customer}=await requirePortalCustomer(request);const [shipments,events]=await Promise.all([env.DB.prepare(`SELECT s.id,s.shipment_number,o.order_number,s.status,s.current_location,s.estimated_delivery_at,s.actual_delivery_at,s.signed_by,o.origin_city,o.destination_city,o.cargo_description FROM shipments s JOIN transport_orders o ON o.id=s.order_id WHERE s.organization_id=? AND s.customer_id=? ORDER BY s.updated_at DESC`).bind(user.organizationId,customer.id).all<Shipment>(),env.DB.prepare(`SELECT e.id,e.shipment_id,e.status,e.location,e.description,e.event_at FROM shipment_events e JOIN shipments s ON s.id=e.shipment_id WHERE s.organization_id=? AND s.customer_id=? AND e.visible_to_customer=1 ORDER BY e.event_at DESC`).bind(user.organizationId,customer.id).all<Event>()]);return{shipments:shipments.results,events:events.results}}
export function meta(){return[{title:"运输轨迹 | 欧凌客户门户"}]}
const labels:Record<string,string>={booked:"已订舱",picked_up:"已提货",in_transit:"运输中",customs:"清关中",out_for_delivery:"运输中",delivered:"已签收",exception:"运输异常",cancelled:"已取消"};
export default function PortalTracking({loaderData}:Route.ComponentProps){return <><header className="page-header"><div><p className="eyebrow">TRACK & TRACE</p><h1>运输轨迹</h1><p>查看当前运输状态、预计送达和客户可见节点。</p></div></header>{loaderData.shipments.length?<section className="panel portal-tracking-workbench"><div className="panel-header"><div><h2>运输任务</h2><p>运单状态、当前位置和预计送达集中显示。</p></div></div><div className="table-wrap portal-shipment-table"><table><thead><tr><th>运单 / 订单</th><th>线路</th><th>货物</th><th>当前位置</th><th>预计 / 实际送达</th><th>签收人</th><th>状态</th></tr></thead><tbody>{loaderData.shipments.map(s=><tr key={s.id}><td><strong>{s.shipment_number}</strong><small>{s.order_number}</small></td><td>{s.origin_city} → {s.destination_city}</td><td>{s.cargo_description}</td><td>{s.current_location||"待更新"}</td><td>{s.actual_delivery_at?new Date(s.actual_delivery_at).toLocaleString("zh-CN"):s.estimated_delivery_at?new Date(s.estimated_delivery_at).toLocaleString("zh-CN"):"待定"}</td><td>{s.signed_by||"—"}</td><td><span className={`status-pill ${s.status==='exception'?'danger':''}`}>{labels[s.status]||s.status}</span></td></tr>)}</tbody></table></div><div className="panel-header"><div><h2>客户可见节点记录</h2><p>按最新发生时间排列，保留运单、地点和节点说明。</p></div></div><div className="table-wrap portal-event-table"><table><thead><tr><th>运单</th><th>订单</th><th>节点说明</th><th>地点</th><th>发生时间</th><th>状态</th></tr></thead><tbody>{loaderData.events.map(e=>{const shipment=loaderData.shipments.find(s=>s.id===e.shipment_id);return <tr key={e.id}><td><strong>{shipment?.shipment_number||"—"}</strong></td><td>{shipment?.order_number||"—"}</td><td>{e.description}</td><td>{e.location||"—"}</td><td>{new Date(e.event_at).toLocaleString("zh-CN")}</td><td>{labels[e.status]||e.status}</td></tr>})}{!loaderData.events.length&&<tr><td colSpan={6} className="empty-state">暂无客户可见运输节点。</td></tr>}</tbody></table></div></section>:<p className="empty-state">当前没有执行中的运单。</p>}</>}
